import type {
  IRodConfig,
  IHookConfig,
  ILineConfig,
  IReelConfig,
  IGadgetConfig,
} from '../../types';

import vLure from '@/assets/ui/vibrating_lure.webp';
import sLure from '@/assets/ui/spoon_lure.webp';
import wLure from '@/assets/ui/wobbler_lure.webp';

import rodClassic from '@/assets/ui/casting_rod.webp';
import rodSpinning from '@/assets/ui/spinning_rod.webp';
import reelIcon from '@/assets/ui/reel.webp';
import hookIcon from '@/assets/ui/fishing_hook.webp';
import feederIcon from '@/assets/ui/feeder.webp';
import lineIcon from '@/assets/ui/fishing_line.webp';

import echoSounderIcon from '@/assets/ui/echo_sounder.webp';
import repairKitIcon from '@/assets/ui/repair_kit.webp';

export const SHOP_RODS: IRodConfig[] = [
  // --- Float Rods (8 Items) ---
  {
    id: 'rod_starter',
    name: 'Bamboo Stick',
    description: 'A sturdy but basic bamboo rod.',
    price: 0,
    maxWeight: 4.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_basic',
    name: 'Fiberglass Rod',
    description: 'Decent beginner rod with some flex.',
    price: 500,
    maxWeight: 10.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_amateur',
    name: 'Composite Tele-Rod',
    description: 'Sturdy composite build with great action.',
    price: 1500,
    maxWeight: 20.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_pro',
    name: 'Carbon Match Rod',
    description: 'Strong, lightweight, professional grade.',
    price: 4000,
    maxWeight: 35.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_advanced',
    name: 'Kevlar Match Rod',
    description: 'Kevlar-reinforced layers for intense battles.',
    price: 9000,
    maxWeight: 52.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_titanium',
    name: 'Titanium Beast',
    description: 'Unbreakable rod for monster fish.',
    price: 17000,
    maxWeight: 70.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_nanotube',
    name: 'High-Modulus Carbon',
    description:
      'State-of-the-art weave, handles the heaviest freshwater giants.',
    price: 30000,
    maxWeight: 85.0,
    rodCategory: 'float',
    icon: rodClassic,
  },
  {
    id: 'rod_kraken',
    name: 'Heavy Duty Tele-Rod',
    description: 'Legendary, heavy-duty deep-sea rod designed to lift krakens.',
    price: 52000,
    maxWeight: 100.0,
    rodCategory: 'float',
    icon: rodClassic,
  },

  // --- Spinning Rods (8 Items) ---
  {
    id: 'rod_spinning_basic',
    name: 'Basic Spinning',
    description: 'Lightweight rod designed for active lure work.',
    price: 0,
    maxWeight: 4.5,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_amateur',
    name: 'Light Spinning',
    description: 'Fast-action blank perfect for soft baits.',
    price: 600,
    maxWeight: 11.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_classic',
    name: 'Medium-Light Spin',
    description: 'Versatile spinning rod with excellent sensitivity.',
    price: 1800,
    maxWeight: 22.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_pro',
    name: 'Graphite Master',
    description: 'Excellent sensitivity for feeling every nibble.',
    price: 4500,
    maxWeight: 36.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_advanced',
    name: 'Medium-Heavy Spin',
    description: 'Ultra-tough glass fiber blend for strong strikes.',
    price: 10000,
    maxWeight: 54.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_ultra',
    name: 'Nano-Carbon Spin',
    description: 'The peak of spinning technology.',
    price: 20000,
    maxWeight: 70.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_ocean',
    name: 'Heavy Casting Spin',
    description:
      'Extremely rigid backbone for fighting large marine predators.',
    price: 34000,
    maxWeight: 85.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
  {
    id: 'rod_spinning_leviathan',
    name: 'Trophy Saltwater Spin',
    description:
      'The ultimate spinning weapon. Capable of landing sea leviathans.',
    price: 55000,
    maxWeight: 100.0,
    rodCategory: 'spinning',
    icon: rodSpinning,
  },
];

export const SHOP_HOOKS: IHookConfig[] = [
  {
    id: 'hook_rusted',
    name: 'Rusted Hook',
    description: 'Dull and brittle.',
    price: 0,
    maxWeight: 4.0,
    quality: 0.85,
    rigType: 'float',
    icon: hookIcon,
  },
  {
    id: 'hook_iron',
    name: 'Iron Hook',
    description: 'Standard hook, holds okay.',
    price: 60,
    maxWeight: 11.0,
    quality: 0.92,
    rigType: 'float',
    icon: hookIcon,
  },
  {
    id: 'hook_steel',
    name: 'Carbon Steel Hook',
    description: 'Sharp and very hard to bend.',
    price: 200,
    maxWeight: 25.0,
    quality: 0.97,
    rigType: 'float',
    icon: hookIcon,
  },
  {
    id: 'hook_barbed',
    name: 'Barbed Laser-Sharpened',
    description: 'Fish rarely escape this.',
    price: 650,
    maxWeight: 65.0,
    quality: 0.99,
    rigType: 'float',
    icon: hookIcon,
  },
  {
    id: 'hook_feeder_basic',
    name: 'Basic Feeder',
    description: 'A classic bottom rig. Always rests on the bottom.',
    price: 120,
    maxWeight: 15.0,
    quality: 0.9,
    rigType: 'feeder',
    icon: feederIcon,
  },
  {
    id: 'hook_feeder_pro',
    name: 'Pro Feeder',
    description: 'Long-distance feeder cage with a sharp hook.',
    price: 1200,
    maxWeight: 45.0,
    quality: 0.98,
    rigType: 'feeder',
    icon: feederIcon,
  },
  {
    id: 'lure_vibrotail',
    name: 'Vibrotail 3"',
    description: 'Soft plastic lure with realistic tail action. Sinks slowly.',
    price: 100,
    maxWeight: 18.0,
    quality: 0.93,
    rigType: 'spinning',
    lureType: 'vibrotail',
    icon: vLure,
  },
  {
    id: 'lure_spoon',
    name: 'Silver Spoon',
    description: 'Classic metal lure. Sinks quickly and flashes in the light.',
    price: 300,
    maxWeight: 35.0,
    quality: 0.96,
    rigType: 'spinning',
    lureType: 'spoon',
    icon: sLure,
  },
  {
    id: 'lure_wobbler',
    name: 'Deep-Diver Wobbler',
    description: 'Floats when still, but dives deep when pulled.',
    price: 1500,
    maxWeight: 65.0,
    quality: 0.98,
    rigType: 'spinning',
    lureType: 'wobbler',
    icon: wLure,
  },
  {
    id: 'hook_tungsten',
    name: 'Forged Steel Hook 4/0',
    description: 'Virtually indestructible hook with high penetration power.',
    price: 2000,
    maxWeight: 82.0,
    quality: 0.99,
    rigType: 'float',
    icon: hookIcon,
  },
  {
    id: 'hook_kraken',
    name: 'Forged Sea Hook 8/0',
    description:
      "Massive, forged titanium hook for the ocean's strongest beasts.",
    price: 4500,
    maxWeight: 100.0,
    quality: 0.99,
    rigType: 'float',
    icon: hookIcon,
  },
  {
    id: 'hook_feeder_heavy',
    name: 'Heavy Bottom Rig 100g',
    description: 'Reinforced cage and hook for deep sea bottom feeders.',
    price: 2200,
    maxWeight: 80.0,
    quality: 0.99,
    rigType: 'feeder',
    icon: feederIcon,
  },
  {
    id: 'hook_feeder_titan',
    name: 'Trophy Bottom Rig 150g',
    description:
      'Industrial-grade heavy bottom rig for 100kg freshwater giants.',
    price: 4500,
    maxWeight: 100.0,
    quality: 0.99,
    rigType: 'feeder',
    icon: feederIcon,
  },
  {
    id: 'lure_spoon_heavy',
    name: 'Heavy Casting Spoon 45g',
    description:
      'Huge reflective metal lure designed for active pelagic predators.',
    price: 2500,
    maxWeight: 80.0,
    quality: 0.98,
    rigType: 'spinning',
    lureType: 'spoon',
    icon: sLure,
  },
  {
    id: 'lure_wobbler_titan',
    name: 'Deep Diver Wobbler 150F',
    description:
      'Extra-large wobbler with hydrodynamic dive lips for 100kg leviathans.',
    price: 5000,
    maxWeight: 100.0,
    quality: 0.99,
    rigType: 'spinning',
    lureType: 'wobbler',
    icon: wLure,
  },
];

export const SHOP_LINES: ILineConfig[] = [
  {
    id: 'line_thread',
    name: 'Cotton Thread',
    description: 'Breaks if you look at it wrong.',
    price: 0,
    maxWeight: 3.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_mono',
    name: 'Monofilament 15lb',
    description: 'Standard cheap line.',
    price: 150,
    maxWeight: 9.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_fluorocarbon_basic',
    name: 'Fluorocarbon 25lb',
    description: 'Nearly invisible, great for medium lakes.',
    price: 500,
    maxWeight: 18.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_fluoro',
    name: 'Fluorocarbon 35lb',
    description: 'Highly resilient and nearly invisible underwater.',
    price: 1000,
    maxWeight: 32.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_braid_light',
    name: 'Braided Line PE #3.0',
    description: 'Excellent sensitivity and great strength.',
    price: 2000,
    maxWeight: 50.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_braid',
    name: 'Braided Line PE #5.0',
    description: 'Incredibly strong, but highly visible.',
    price: 4000,
    maxWeight: 68.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_tungsten',
    name: 'Heavy Braided PE #6.0',
    description:
      'Heavy tungsten-infused braided line. Ultra thin but incredibly tough.',
    price: 6500,
    maxWeight: 85.0,
    totalLength: 300,
    icon: lineIcon,
  },
  {
    id: 'line_nanofiber',
    name: 'Professional Braid PE #8.0',
    description:
      'Next-generation synthetic fiber. Completely unbreakable and crystal clear.',
    price: 11000,
    maxWeight: 100.0,
    totalLength: 300,
    icon: lineIcon,
  },
];

export const SHOP_REELS: IReelConfig[] = [
  {
    id: 'reel_handmade',
    name: 'Wooden Spool',
    description: 'Barely reels the line in.',
    price: 0,
    speed: 1.0,
    maxWeight: 3.5,
    icon: reelIcon,
  },
  {
    id: 'reel_basic',
    name: 'Basic Spinner',
    description: 'Does the job for small/medium fish.',
    price: 400,
    speed: 1.1,
    maxWeight: 10.0,
    icon: reelIcon,
  },
  {
    id: 'reel_amateur',
    name: 'Rear-Drag Spinner',
    description: 'Reliable mechanical drag with bronze gears.',
    price: 1200,
    speed: 1.14,
    maxWeight: 20.0,
    icon: reelIcon,
  },
  {
    id: 'reel_multi',
    name: 'Multiplier Reel',
    description: 'Fast retrieval, smooth drag.',
    price: 3000,
    speed: 1.18,
    maxWeight: 35.0,
    icon: reelIcon,
  },
  {
    id: 'reel_advanced',
    name: 'Front-Drag Power Reel',
    description: 'Extremely durable drag built to halt powerful runs.',
    price: 7000,
    speed: 1.21,
    maxWeight: 52.0,
    icon: reelIcon,
  },
  {
    id: 'reel_electric',
    name: 'Power-Assist Reel',
    description: 'Winch-like power.',
    price: 16000,
    speed: 1.24,
    maxWeight: 70.0,
    icon: reelIcon,
  },
  {
    id: 'reel_marine',
    name: 'Saltwater Heavy Reel',
    description:
      'Saltwater protected, massive torque, highly optimized for large prey.',
    price: 28000,
    speed: 1.27,
    maxWeight: 85.0,
    icon: reelIcon,
  },
  {
    id: 'reel_poseidon',
    name: 'Big Game Multiplier',
    description:
      'A motorized masterpiece capable of reeling in a shark with ease.',
    price: 52000,
    speed: 1.3,
    maxWeight: 100.0,
    icon: reelIcon,
  },
];

export const SHOP_GADGETS: IGadgetConfig[] = [
  {
    id: 'echo_sounder',
    name: 'Echo Sounder',
    description: 'Electronic device that shows fish presence and depth.',
    price: 5000,
    icon: echoSounderIcon,
  },
  {
    id: 'repair_kit',
    name: 'Repair Kit',
    description: 'Restores durability to damaged rods and reels.',
    price: 600,
    icon: repairKitIcon,
  },
];
